

logging:
  dir: '~/logs' 

handlers:
  - endpoint: /webhooks/first
    auth:
      token: 
        - alpha
        - beta
      validator: list
    name: "handle repo A's update"
    run: |
      echo "$PIRATE_BODY" > ~/body.json 
      echo "$PIRATE_HEADERS" > ~/headers.json

