name: CI
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read 

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.64

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - run: 'go test -v ./...'

  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - run: 'apt update && apt install -yq make podman'
      - run: 'make run-integration-test'
