name: Deploy

on:
  push:
    tags: 
      - '*'
    branches:
      - master
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - run: 'sudo apt update && sudo apt install -yq make podman'
      - name: set image tag version
        run: |
          TAG_VERSION=latest 
          if test "${{ github.ref_type }}" = "tag"; then
            TAG_VERSION="${{ github.ref_name }}"
          fi 

          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
          echo "tag version: $TAG_VERSION"
      - run: |
          make build-img TAG_VERSION="${{ env.TAG_VERSION }}"

      - run: |
          podman login \
            -u "${{ vars.REGISTRY_USER }}" \
            -p "${{ secrets.REGISTRY_TOKEN }}" ${{ vars.REGISTRY_NAME }}

      - run: |
          podman push aalbacetef/pirate:${{ vars.TAG_VERSION }} 
