name: Deploy

on:
  push:
    tags: 
      - '*'
    branches:
      - master
  pull_request:

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - run: 'sudo apt update && sudo apt install -yq make podman'
      - run: make build-img 
      - run: 'podman save -o image-build.tar aalbacetef/pirate:latest' 
      - uses: actions/upload-artifact@v4
        with:
          name: build tarball
          path: image-build.tar

